In [1]:
import pandas as pd
import glob
import os
import numpy as np
from sqlalchemy import create_engine
from datetime import date

#Import raw CSVs and merge them together into one dataframe
path = r'C:\Course Work\tableau-challenge\Raw CSVs'
all_files = glob.glob(os.path.join(path, "*.csv"))

df_from_each_file = (pd.read_csv(f) for f in all_files)
citibike_records_df   = pd.concat(df_from_each_file, ignore_index=True)

In [2]:
#Check that all records merged correctly
citibike_records_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,330,2019-06-01 00:00:01.5000,2019-06-01 00:05:31.7600,3602.0,31 Ave & 34 St,40.763154,-73.920827,3570.0,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1
1,830,2019-06-01 00:00:04.2400,2019-06-01 00:13:55.1470,3054.0,Greene Ave & Throop Ave,40.689493,-73.942061,3781.0,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2
2,380,2019-06-01 00:00:06.0190,2019-06-01 00:06:26.7790,229.0,Great Jones St,40.727434,-73.993790,326.0,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441.0,E 52 St & 2 Ave,40.756014,-73.967416,3159.0,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993289,203,2020-02-29 23:58:48.0230,2020-03-01 00:02:11.6640,3737.0,Stanton St & Norfolk St,40.720747,-73.986274,317.0,E 6 St & Avenue B,40.724537,-73.981854,39094,Subscriber,1993,2
9993290,357,2020-02-29 23:58:52.5640,2020-03-01 00:04:50.5370,546.0,E 30 St & Park Ave S,40.744449,-73.983035,3463.0,E 16 St & Irving Pl,40.735367,-73.987974,40722,Subscriber,1966,2
9993291,169,2020-02-29 23:58:54.5820,2020-03-01 00:01:43.7770,3043.0,Lewis Ave & Decatur St,40.681460,-73.934903,3052.0,Lewis Ave & Madison St,40.686312,-73.935775,28696,Subscriber,1994,1
9993292,738,2020-02-29 23:58:58.8110,2020-03-01 00:11:17.7390,3255.0,8 Ave & W 31 St,40.750585,-73.994685,497.0,E 17 St & Broadway,40.737050,-73.990093,19975,Subscriber,1999,1
9993293,960,2020-02-29 23:59:35.6070,2020-03-01 00:15:35.6490,379.0,W 31 St & 7 Ave,40.749156,-73.991600,3744.0,1 Ave & E 5 St,40.725864,-73.986389,38651,Subscriber,1990,1

In [3]:
#Convert starttime to datetime format
citibike_records_df['starttime'] = pd.to_datetime(citibike_records_df['starttime'])

In [4]:
#Create new Season column that classifies records as either Summer or Winter based on date
citibike_records_df['season'] = np.where(citibike_records_df['starttime'] < pd.Timestamp(date(2019,9,1)), 'Summer', 'Winter')

citibike_records_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,season
0,330,2019-06-01 00:00:01.500,2019-06-01 00:05:31.7600,3602.0,31 Ave & 34 St,40.763154,-73.920827,3570.0,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1,Summer
1,830,2019-06-01 00:00:04.240,2019-06-01 00:13:55.1470,3054.0,Greene Ave & Throop Ave,40.689493,-73.942061,3781.0,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2,Summer
2,380,2019-06-01 00:00:06.019,2019-06-01 00:06:26.7790,229.0,Great Jones St,40.727434,-73.993790,326.0,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2,Summer
3,1155,2019-06-01 00:00:06.776,2019-06-01 00:19:22.5380,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1,Summer
4,1055,2019-06-01 00:00:07.520,2019-06-01 00:17:42.5580,441.0,E 52 St & 2 Ave,40.756014,-73.967416,3159.0,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993289,203,2020-02-29 23:58:48.023,2020-03-01 00:02:11.6640,3737.0,Stanton St & Norfolk St,40.720747,-73.986274,317.0,E 6 St & Avenue B,40.724537,-73.981854,39094,Subscriber,1993,2,Winter
9993290,357,2020-02-29 23:58:52.564,2020-03-01 00:04:50.5370,546.0,E 30 St & Park Ave S,40.744449,-73.983035,3463.0,E 16 St & Irving Pl,40.735367,-73.987974,40722,Subscriber,1966,2,Winter
9993291,169,2020-02-29 23:58:54.582,2020-03-01 00:01:43.7770,3043.0,Lewis Ave & Decatur St,40.681460,-73.934903,3052.0,Lewis Ave & Madison St,40.686312,-73.935775,28696,Subscriber,1994,1,Winter
9993292,738,2020-02-29 23:58:58.811,2020-03-01 00:11:17.7390,3255.0,8 Ave & W 31 St,40.750585,-73.994685,497.0,E 17 St & Broadway,40.737050,-73.990093,19975,Subscriber,1999,1,Winter
9993293,960,2020-02-29 23:59:35.607,2020-03-01 00:15:35.6490,379.0,W 31 St & 7 Ave,40.749156,-73.991600,3744.0,1 Ave & E 5 St,40.725864,-73.986389,38651,Subscriber,1990,1,Winter

In [5]:
#Calculate Age of customers baxed on Birth Year
citibike_records_df['age'] = (2020 - citibike_records_df['birth year'])

citibike_records_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,season,age
0,330,2019-06-01 00:00:01.500,2019-06-01 00:05:31.7600,3602.0,31 Ave & 34 St,40.763154,-73.920827,3570.0,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1,Summer,28
1,830,2019-06-01 00:00:04.240,2019-06-01 00:13:55.1470,3054.0,Greene Ave & Throop Ave,40.689493,-73.942061,3781.0,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2,Summer,33
2,380,2019-06-01 00:00:06.019,2019-06-01 00:06:26.7790,229.0,Great Jones St,40.727434,-73.993790,326.0,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2,Summer,30
3,1155,2019-06-01 00:00:06.776,2019-06-01 00:19:22.5380,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1,Summer,33
4,1055,2019-06-01 00:00:07.520,2019-06-01 00:17:42.5580,441.0,E 52 St & 2 Ave,40.756014,-73.967416,3159.0,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1,Summer,47

In [6]:
#Exclude all rows where customer is over 100 years old
citibike_records_filtered_df= citibike_records_df[citibike_records_df['birth year'] >= 1920]
citibike_records_filtered_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,season,age
0,330,2019-06-01 00:00:01.500,2019-06-01 00:05:31.7600,3602.0,31 Ave & 34 St,40.763154,-73.920827,3570.0,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1,Summer,28
1,830,2019-06-01 00:00:04.240,2019-06-01 00:13:55.1470,3054.0,Greene Ave & Throop Ave,40.689493,-73.942061,3781.0,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2,Summer,33
2,380,2019-06-01 00:00:06.019,2019-06-01 00:06:26.7790,229.0,Great Jones St,40.727434,-73.993790,326.0,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2,Summer,30
3,1155,2019-06-01 00:00:06.776,2019-06-01 00:19:22.5380,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1,Summer,33
4,1055,2019-06-01 00:00:07.520,2019-06-01 00:17:42.5580,441.0,E 52 St & 2 Ave,40.756014,-73.967416,3159.0,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1,Summer,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993289,203,2020-02-29 23:58:48.023,2020-03-01 00:02:11.6640,3737.0,Stanton St & Norfolk St,40.720747,-73.986274,317.0,E 6 St & Avenue B,40.724537,-73.981854,39094,Subscriber,1993,2,Winter,27
9993290,357,2020-02-29 23:58:52.564,2020-03-01 00:04:50.5370,546.0,E 30 St & Park Ave S,40.744449,-73.983035,3463.0,E 16 St & Irving Pl,40.735367,-73.987974,40722,Subscriber,1966,2,Winter,54
9993291,169,2020-02-29 23:58:54.582,2020-03-01 00:01:43.7770,3043.0,Lewis Ave & Decatur St,40.681460,-73.934903,3052.0,Lewis Ave & Madison St,40.686312,-73.935775,28696,Subscriber,1994,1,Winter,26
9993292,738,2020-02-29 23:58:58.811,2020-03-01 00:11:17.7390,3255.0,8 Ave & W 31 St,40.750585,-73.994685,497.0,E 17 St & Broadway,40.737050,-73.990093,19975,Subscriber,1999,1,Winter,21
9993293,960,2020-02-29 23:59:35.607,2020-03-01 00:15:35.6490,379.0,W 31 St & 7 Ave,40.749156,-73.991600,3744.0,1 Ave & E 5 St,40.725864,-73.986389,38651,Subscriber,1990,1,Winter,30

In [7]:
#Export dataframe as csv file
citibike_records_filtered_df.to_csv("combined_cleaned_citibike_records.csv", index=False)